:Author: bambi_meg
:Email: {AuthorEmail}
:Date: 06/08/2021
:Revision: version#
:License: Public Domain

= Project: {Project}

Developed a smart room system comprising of password protected door lock, 
automatic room lighting and smoke detector using Arduino and sensors

== Step 1: Installation

1. Open this file
2. Use it for making a smart room system, add or delete functionalities
   by editing as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 ReadMe.adoc         => this file
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── layout.png      => (optional) an image of the required schematics/circuit diagram
 
....

=== License
This project is released under a {License} License.

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
